version: '3.7'
services:
  db:
    image: mariadb:10.4
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
     - .env

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1-php7.2
    ports:
      - "8000:80"
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html/wp-content
    restart: always
    env_file:
     - .env
  
  adminer:
    depends_on:
      - db
    image: adminer:latest
    ports:
      - 9000:8080

volumes:
  db_data: {}
